### ISSUE TITLE
샘플페이지

### ISSUE THREAD

**Issue by cha2hyun** [wonjun1995/mole-camping#1]
샘플페이지 있으면 좋을 것 같아요

**Comment by ethan-mino** [comment]
안녕하세요 OREO입니다.
해당 사항은 아덴 팀장님께 문의해주세요!
감사합니다.

**Comment by cha2hyun** [comment]
> 안녕하세요 OREO입니다. 해당 사항은 아덴 팀장님께 문의해주세요! 감사합니다.

네.
